service: test-s3

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::test-s3/*"

# Expose function to public API for POST requests.
functions:
  fileUpload:
    handler: fileUpLoaderHome.handler
    events:
      - http:
          path: fileUpload
          method: post
          cors: true

# Give service access to the specific S3 bucket.
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "test-s3-v"
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
