service: imageupload

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    bucketName: ${self:custom.bucketName}
    imageUploadBucket: ${self:custom.imageUploadBucket}
    region: ap-northe

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  individually: true

custom:
  bucketName: sls-upload-s3
  imageUploadBucket: my-image-upload-bucket-demo

functions:
  imageUpload:
    handler: imageUpload.handler
    events:
      - http:
          path: image-upload
          method: POST
          cors: true

resources:
  Resources:
    ImageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucket}
        AccessControl: PublicRead
